##Constants file for the static values

CASSANDRA_USER = 'nexti_app'
CASSANDRA_PASSWORD = 'spark'
CASSANDRA_HOST = '172.22.229.194,172.22.229.197,172.22.229.196'
CASSANDRA_SCHEMA= 'nexti_ay_release_hemant'
LOG_LEVEL_INFO = 'INFO'
LOG_LEVEL_DEBUG = 'DEBUG'
LOG_LEVEL_TRACE = 'TRACE'
LOG_DELIMETER = '|'
DIRECTORY_DELIMETER = '/'
STATS_MESSAGE_TYPE_IDX = 5
STATS_BUSINESS_KEY_IDX = 6
STATS_CUSTOM_MESSAGE_IDX = 7
MESSAGE_TYPE_SBR = "SBR"
MESSAGE_TYPE_TKT = "TOF"
MESSAGE_TYPE_FLT = "FLD"
MESSAGE_TYPE_EMD = "EMD"


#QUERY PARAMETERS
SELECT_STMT = "SELECT "
FROM_STMT = " FROM "
BOOKING_TABLE_NAME = "BOOKING"
BOOKING_BUSINESS_KEY = "PNR_RLOC, PNR_CREATION_DATE, BKG_TATTOO"
TICKET_TABLE_NAME = "TICKET"
TICKET_BUSINESS_KEY = "TKT_PRIMARY_NUMBER, TKT_DATE_OF_ISSUE, TKT_SOURCE"
EMD_TABLE_NAME = "EMD_COUPON"
EMD_BUSINESS_KEY = "EMD_PRIMARY_NUMBER, EMD_DATE_OF_ISSUE"
FLIGHT_BUSINESS_KEY = "MKT_FLT_CARRIER_CODE, MKT_FLT_NUMBER, MKT_FLT_DATE, MKT_FLT_ALPHA_SUFFIX"
FLIGHT_TABLE_NAME = "SEGMENT_FLIGHT_LEG_BY_MKT"
FEED_EXCEPTION_BUSINESS_KEY = "FLT_CARRIER_CODE, FLT_NUMBER ,FLT_DATE, FLT_ALPHA_SUFFIX, STATUS"
FEED_EXCEPTION_TABLE_NAME = "FEED_EXCEPTION_FLD"
EXCEPTIONS_BUSINESS_KEY = "FEED, DATE, PARTITION_KEY"
EXCEPTIONS_TABLE_NAME = "EXCEPTIONS"

#XML Extract
ELEM_BOOKING = "Booking"
ELEM_PNR = "PNR"
ELEM_TICKET = "Ticket"
ELEM_FLIGHT = "Flight"
ELEM_EMD = "EMD"